workflows:
  build-ipa-only:
    name: Build iOS IPA Only
    environment:
      xcode: latest
    triggering:
      events:
        - push
    scripts:
      - name: Use signing profiles
        script: |
          xcode-project use-profiles

      - name: Generate ExportOptions.plist
        script: |
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

      - name: Build and export IPA
        script: |
          xcode-project build-ipa \
            --project "TDS Video.xcodeproj" \
            --scheme "TDS Video" \
            --export-options-plist ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

code_signing:
  automatic_code_signing:
    team_id: C3Z5URCHGS
    app_store_connect_credential:
      key_id: "23ZMF48P8Z"
      issuer_id: "fcb8faeb-1e16-4bcd-9083-9186811c0262"
      key: |
        -----BEGIN PRIVATE KEY-----
        MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOTj62dXMg9eCpyqD
        YRLmuE5BfodmezSB42cMxKNw0HigCgYIKoZIzj0DAQehRANCAAR4PNM2kqyjI03p
        d4eh2gMpNNOfzZYo0+QgB+gT4KmA0EcHflfO3KH09w4l1wp6+B1W8JSQWhSN8uv/
        5Qb/hjTI
        -----END PRIVATE KEY-----
