signing:
  ios_signing:
    provisioning_profiles:
      com.nft.colony: TDS-Car
      com.nft.colony.UploadVideo: UploadVideo
      com.nft.colony.Video3: Video3
      com.nft.colony.ScreenRec: ScreenRec
      com.nft.colony.ScreenRecSetupUI: ScreenRecSetupUI
      com.nft.colony.Carplayintent: CarPlayIntent
      com.nft.colony.CarplayintentUI: CarplayintentUI

workflows:
  build-ipa-only:
    name: Build iOS IPA Only
    environment:
      xcode: latest
    triggering:
      events:
        - push
    scripts:
      - name: Configure App Store Connect API Key
        script: |
          mkdir -p ~/private_keys
          cat > ~/private_keys/AuthKey_23ZMF48P8Z.p8 <<EOF
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOTj62dXMg9eCpyqD
          YRLmuE5BfodmezSB42cMxKNw0HigCgYIKoZIzj0DAQehRANCAAR4PNM2kqyjI03p
          d4eh2gMpNNOfzZYo0+QgB+gT4KmA0EcHflfO3KH09w4l1wp6+B1W8JSQWhSN8uv/
          5Qb/hjTI
          -----END PRIVATE KEY-----
          EOF
          chmod 600 ~/private_keys/AuthKey_23ZMF48P8Z.p8
          export API_KEY_PATH=~/private_keys/AuthKey_23ZMF48P8Z.p8
          export API_KEY_ID=23ZMF48P8Z
          export API_KEY_ISSUER_ID=fcb8faeb-1e16-4bcd-9083-9186811c0262

      - name: Update Team ID and Signing Settings
        script: |
          sed -i '' 's/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = C3Z5URCHGS;/g' "TDS Video.xcodeproj/project.pbxproj"
          sed -i '' 's/CODE_SIGN_STYLE = .*;/CODE_SIGN_STYLE = Manual;/g' "TDS Video.xcodeproj/project.pbxproj"
          sed -i '' '/PROVISIONING_PROFILE_SPECIFIER/d' "TDS Video.xcodeproj/project.pbxproj"
          sed -i '' '/PROVISIONING_PROFILE = .*;/d' "TDS Video.xcodeproj/project.pbxproj"
          sed -i '' 's/SWIFT_OPTIMIZATION_LEVEL = .*;/SWIFT_OPTIMIZATION_LEVEL = "-Onone";/g' "TDS Video.xcodeproj/project.pbxproj"
          echo "✅ Code signing settings updated."
          grep -E "DEVELOPMENT_TEAM|CODE_SIGN_STYLE|SWIFT_OPTIMIZATION_LEVEL" "TDS Video.xcodeproj/project.pbxproj"

      - name: Generate ExportOptions.plist
        script: |
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
            <key>teamID</key>
            <string>C3Z5URCHGS</string>
          </dict>
          </plist>
          EOF

      - name: Build and Export IPA
        script: |
          set -exo pipefail
          rm -rf build
          xcodebuild archive \
            -project "TDS Video.xcodeproj" \
            -scheme "TDS Video" \
            -archivePath build/ios/TDS_Video.xcarchive \
            -destination 'generic/platform=iOS' \
            DEVELOPMENT_TEAM=C3Z5URCHGS \
            CODE_SIGN_STYLE=Manual \
            -allowProvisioningUpdates
          xcodebuild -exportArchive \
            -archivePath build/ios/TDS_Video.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates
          echo "Build artifacts:"
          ls -lR build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
