workflows:
  build-ipa-only:
    name: Build iOS IPA Only
    environment:
      xcode: latest
      vars:
        XCODE_SCHEME: "TDS Video"
        XCODE_PROJECT: "TDS Video.xcodeproj"
        BUNDLE_ID: "com.nft.colony"
    triggering:
      events:
        - push
    scripts:
      - name: Build and archive the app
        script: |
          xcodebuild clean

          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$HOME/build/$XCODE_SCHEME.xcarchive" \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=C3Z5URCHGS \
            PROVISIONING_PROFILE_SPECIFIER="" \
            -allowProvisioningUpdates


      - name: Export IPA
        script: |
          cat <<EOF > exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath "$HOME/build/$XCODE_SCHEME.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$HOME/export"

    artifacts:
      - export/*.ipa

code_signing:
  automatic_code_signing:
    app_store_connect_credential:
      key_id: "23ZMF48P8Z"
      issuer_id: "fcb8faeb-1e16-4bcd-9083-9186811c0262"
      key: |
        -----BEGIN PRIVATE KEY-----
        MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOTj62dXMg9eCpyqD
        YRLmuE5BfodmezSB42cMxKNw0HigCgYIKoZIzj0DAQehRANCAAR4PNM2kqyjI03p
        d4eh2gMpNNOfzZYo0+QgB+gT4KmA0EcHflfO3KH09w4l1wp6+B1W8JSQWhSN8uv/
        5Qb/hjTI
        -----END PRIVATE KEY-----
    team_id: C3Z5URCHGS
