workflows:
  build-ipa-only:
    name: Build iOS IPA Only
    environment:
      xcode: latest
      ios_signing:
        certificates:
          - TDS-car
        provisioning_profiles:
          com.nft.colony: TDS-Car
          com.nft.colony.UploadVideo: UploadVideo
          com.nft.colony.Video3: Video3
          com.nft.colony.ScreenRec: ScreenRec
          com.nft.colony.ScreenRecSetupUI: ScreenRecSetupUI
          com.nft.colony.Carplayintent: CarPlayIntent
          com.nft.colony.CarplayintentUI: CarplayintentUI

    triggering:
      events:
        - push

    scripts:
      - name: Use provisioning profiles
        script: xcode-project use-profiles

      - name: Configure App Store Connect API Key
        script: |
          mkdir -p ~/private_keys
          cat > ~/private_keys/AuthKey_23ZMF48P8Z.p8 <<EOF
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOTj62dXMg9eCpyqD
          YRLmuE5BfodmezSB42cMxKNw0HigCgYIKoZIzj0DAQehRANCAAR4PNM2kqyjI03p
          d4eh2gMpNNOfzZYo0+QgB+gT4KmA0EcHflfO3KH09w4l1wp6+B1W8JSQWhSN8uv/
          5Qb/hjTI
          -----END PRIVATE KEY-----
          EOF
          chmod 600 ~/private_keys/AuthKey_23ZMF48P8Z.p8
          export API_KEY_PATH=~/private_keys/AuthKey_23ZMF48P8Z.p8
          export API_KEY_ID=23ZMF48P8Z
          export API_KEY_ISSUER_ID=fcb8faeb-1e16-4bcd-9083-9186811c0262

      - name: Build and Export IPA
        script: |
          set -exo pipefail
          rm -rf build
          xcodebuild archive \
            -project "TDS Video.xcodeproj" \
            -scheme "TDS Video" \
            -archivePath build/ios/TDS_Video.xcarchive \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates
          xcodebuild -exportArchive \
            -archivePath build/ios/TDS_Video.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates

    artifacts:
      - build/ios/ipa/*.ipa
