workflows:
  build-ipa-only:
    name: Build iOS IPA Only
    environment:
      xcode: latest
    triggering:
      events:
        - push
    scripts:
      - name: Configure App Store Connect API Key
        script: |
          # Create directory for API keys
          mkdir -p ~/.appstoreconnect/private_keys
          
          # Write API key to file
          cat <<EOF > ~/.appstoreconnect/private_keys/AuthKey_$APPLE_DEVELOPER_CONNECTION_KEY_ID.p8
          $APPLE_DEVELOPER_CONNECTION_KEY
          EOF
          
          # Set permissions
          chmod 600 ~/.appstoreconnect/private_keys/AuthKey_$APPLE_DEVELOPER_CONNECTION_KEY_ID.p8
          
          # Configure environment variables for Xcode
          export APP_STORE_CONNECT_API_KEY_PATH=~/.appstoreconnect/private_keys/AuthKey_$APPLE_DEVELOPER_CONNECTION_KEY_ID.p8
          export APP_STORE_CONNECT_API_KEY_KEY_ID=$APPLE_DEVELOPER_CONNECTION_KEY_ID
          export APP_STORE_CONNECT_API_KEY_ISSUER_ID=$APPLE_DEVELOPER_CONNECTION_ISSUER_ID
          
          echo "API Key configured at: $APP_STORE_CONNECT_API_KEY_PATH"

      - name: Update Team ID and Signing Settings
        script: |
          # Update all team IDs in project file
          sed -i '' 's/K3S7UENN8E/C3Z5URCHGS/g' "TDS Video.xcodeproj/project.pbxproj"
          
          # Force automatic signing for all targets
          sed -i '' 's/CODE_SIGN_STYLE = .*;/CODE_SIGN_STYLE = Automatic;/g' "TDS Video.xcodeproj/project.pbxproj"
          
          # Set Swift optimization level for debug builds
          sed -i '' 's/SWIFT_OPTIMIZATION_LEVEL = .*;/SWIFT_OPTIMIZATION_LEVEL = "-Onone";/g' "TDS Video.xcodeproj/project.pbxproj"
          
          # Remove provisioning profile specifiers
          sed -i '' '/PROVISIONING_PROFILE_SPECIFIER/d' "TDS Video.xcodeproj/project.pbxproj"
          
          # Verify changes
          echo "Updated settings:"
          grep -E "DEVELOPMENT_TEAM|CODE_SIGN_STYLE|SWIFT_OPTIMIZATION_LEVEL" "TDS Video.xcodeproj/project.pbxproj"

      - name: Generate ExportOptions.plist
        script: |
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
            <key>teamID</key>
            <string>C3Z5URCHGS</string>
          </dict>
          </plist>
          EOF
          
          echo "ExportOptions.plist contents:"
          cat ExportOptions.plist

      - name: Build and Export IPA
        script: |
          set -exo pipefail
          
          # Clean build directory
          rm -rf build
          
          # Build and archive with provisioning updates
          xcodebuild archive \
            -project "TDS Video.xcodeproj" \
            -scheme "TDS Video" \
            -archivePath build/ios/TDS_Video.xcarchive \
            -destination 'generic/platform=iOS' \
            DEVELOPMENT_TEAM=C3Z5URCHGS \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates
          
          # Export IPA for App Store
          xcodebuild -exportArchive \
            -archivePath build/ios/TDS_Video.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates

          echo "Build artifacts:"
          ls -lR build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa

code_signing:
  automatic_code_signing:
    team_id: C3Z5URCHGS
    app_store_connect_credential:
      key_id: "23ZMF48P8Z"
      issuer_id: "fcb8faeb-1e16-4bcd-9083-9186811c0262"
      key: |
        -----BEGIN PRIVATE KEY-----
        MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOTj62dXMg9eCpyqD
        YRLmuE5BfodmezSB42cMxKNw0HigCgYIKoZIzj0DAQehRANCAAR4PNM2kqyjI03p
        d4eh2gMpNNOfzZYo0+QgB+gT4KmA0EcHflfO3KH09w4l1wp6+B1W8JSQWhSN8uv/
        5Qb/hjTI
        -----END PRIVATE KEY-----
