workflows:
  build-ipa-only:
    name: Build iOS IPA Only
    environment:
      xcode: latest
      ios_signing:
        - distribution_type: ad_hoc
          certificate_name: "TDS-car"
          provisioning_profile_name: "UploadVideo"
          bundle_identifier: "com.nft.colony.UploadVideo"
        - distribution_type: ad_hoc
          certificate_name: "TDS-car"
          provisioning_profile_name: "Video3"
          bundle_identifier: "com.nft.colony.Video3"
        - distribution_type: ad_hoc
          certificate_name: "TDS-car"
          provisioning_profile_name: "ScreenRec"
          bundle_identifier: "com.nft.colony.ScreenRec"
        - distribution_type: ad_hoc
          certificate_name: "TDS-car"
          provisioning_profile_name: "ScreenRecSetupUI"
          bundle_identifier: "com.nft.colony.ScreenRecSetupUI"
        - distribution_type: ad_hoc
          certificate_name: "TDS-car"
          provisioning_profile_name: "CarPlayIntent"
          bundle_identifier: "com.nft.colony.Carplayintent"
        - distribution_type: ad_hoc
          certificate_name: "TDS-car"
          provisioning_profile_name: "CarplayintentUI"
          bundle_identifier: "com.nft.colony.CarplayintentUI"

    triggering:
      events:
        - push

    scripts:
      - name: Configure App Store Connect API Key
        script: |
          mkdir -p ~/private_keys
          cat > ~/private_keys/AuthKey_23ZMF48P8Z.p8 <<EOF
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOTj62dXMg9eCpyqD
          YRLmuE5BfodmezSB42cMxKNw0HigCgYIKoZIzj0DAQehRANCAAR4PNM2kqyjI03p
          d4eh2gMpNNOfzZYo0+QgB+gT4KmA0EcHflfO3KH09w4l1wp6+B1W8JSQWhSN8uv/
          5Qb/hjTI
          -----END PRIVATE KEY-----
          EOF
          chmod 600 ~/private_keys/AuthKey_23ZMF48P8Z.p8
          export API_KEY_PATH=~/private_keys/AuthKey_23ZMF48P8Z.p8
          export API_KEY_ID=23ZMF48P8Z
          export API_KEY_ISSUER_ID=fcb8faeb-1e16-4bcd-9083-9186811c0262

      - name: Generate ExportOptions.plist
        script: |
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>teamID</key>
            <string>C3Z5URCHGS</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.nft.colony.UploadVideo</key>
              <string>UploadVideo</string>
              <key>com.nft.colony.Video3</key>
              <string>Video3</string>
              <key>com.nft.colony.ScreenRec</key>
              <string>ScreenRec</string>
              <key>com.nft.colony.ScreenRecSetupUI</key>
              <string>ScreenRecSetupUI</string>
              <key>com.nft.colony.Carplayintent</key>
              <string>CarPlayIntent</string>
              <key>com.nft.colony.CarplayintentUI</key>
              <string>CarplayintentUI</string>
            </dict>
          </dict>
          </plist>
          EOF

      - name: Build and Export IPA
        script: |
          set -exo pipefail
          rm -rf build
          xcodebuild archive \
            -project "TDS Video.xcodeproj" \
            -scheme "TDS Video" \
            -archivePath build/ios/TDS_Video.xcarchive \
            -destination 'generic/platform=iOS' \
            DEVELOPMENT_TEAM=C3Z5URCHGS \
            CODE_SIGN_STYLE=Manual \
            -allowProvisioningUpdates
          xcodebuild -exportArchive \
            -archivePath build/ios/TDS_Video.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates
          echo "Build artifacts:"
          ls -lR build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
